version: "3.9"

services:
  db:
    image: mariadb:10.7.1
    environment:
      MARIADB_ROOT_PASSWORD: rootpass
      MARIADB_CHARSET: utf8mb4
      MARIADB_USER: ${SQL_USER}
      MARIADB_PASSWORD: ${SQL_PASSWORD}
      MARIADB_DATABASE: ${SQL_DATABASE}
    ports:
      - ${SQL_PORT}:3306
    volumes:
      - ./docker/config/mariadb/:/etc/mysql/conf.d
  php:
    build:
      context: https://github.com/MoodyRA/dockerfiles.git#development
      dockerfile: php/8.1/Dockerfile
    #      to test locally
    #      context: ./../dockerfiles/php/8.1
    #      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - ./docker/config/php/cryptools.ini:/usr/local/etc/php/conf.d/cryptools.ini
      - ./docker/config/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./app:/home/${APP_NAME}
  web:
    image: nginx:1.21-alpine
    environment:
      - TZ=Europe/Paris
    depends_on:
      - php
    ports:
      - ${WEB_PORT}:80
    volumes:
      - ./app:/home/${APP_NAME}
      - ./docker/config/nginx/default.conf:/etc/nginx/conf.d/default.conf

