version: "3.9"

services:
  db:
    image: mariadb:10.7.1
    environment:
      MARIADB_ROOT_PASSWORD: rootpass
      MARIADB_CHARSET: utf8mb4
      MARIADB_USER: ${SQL_USER}
      MARIADB_PASSWORD: ${SQL_PASSWORD}
      MARIADB_DATABASE: ${SQL_DATABASE}
    ports:
      - "33200:3306"
  php:
    build:
      context: https://github.com/MoodyRA/dockerfiles.git#development
      dockerfile: php/8.1/Dockerfile
    #      to test locally
    #      context: ./../dockerfiles/php/8.1
    #      dockerfile: Dockerfile
    links:
      - db
    depends_on:
      - db

  nginx:
    image: nginx:1.21-alpine
    environment:
      - TZ=Europe/Paris
    depends_on:
      - db
      - php

